version: '3'

services:
  kitap:
    build: .
    command: python2 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - kitap_redis
  kitap_redis:
    container_name: kitap_redis
    image: redis
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes
    restart: always